{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 HelveticaNeue;}
{\colortbl;\red255\green255\blue255;\red246\green246\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c97255\c97255\c100000;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww20380\viewh15980\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs37\fsmilli18667 \cf0 \cb2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec3 name: CI\
\
\
on: [push, workflow_dispatch]\
\
\
jobs:\
\
  build:\
\
\
    runs-on: windows-latest\
\
\
    steps:\
\
    - name: Download\
\
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip\
\
    - name: Extract\
\
      run: Expand-Archive ngrok.zip\
\
    - name: Auth\
\
      run: .\\ngrok\\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN\
\
      env:\
\
        NGROK_AUTH_TOKEN: $\{\{ secrets.NGROK_AUTH_TOKEN \}\}\
\
    - name: Enable TS\
\
      run: Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server'-name "fDenyTSConnections" -Value 0\
\
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"\
\
    - run: Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -name "UserAuthentication" -Value 1\
\
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)\
\
    - name: Create Tunnel\
\
      run: .\\ngrok\\ngrok.exe tcp 3389}
